name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install
        run: |
          npm install -g @litejs/cli jshint c8
          npm install
      - name: Run lint
        run: lj lint
      - name: Run tests
        run: c8 -r lcov -r text-summary --check-coverage --branches=100 --functions=100 --lines=100 --statements=100 lj test --brief
      - name: Upload coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

